package taskplan

import (
	"fmt"
	"strings"

	"m31labs.dev/reeve/internal/coord"
	"m31labs.dev/reeve/internal/producer"
)

type CreateSpec struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	Workspace   string   `json:"workspace"`
	Priority    string   `json:"priority"`
	DedupKey    string   `json:"dedup_key"`
	Action      string   `json:"action"`
	PriorTask   string   `json:"prior_task,omitempty"`
}

func FromAction(action producer.Action, workspace string) (CreateSpec, error) {
	title := action.Signal.Title
	if strings.TrimSpace(title) == "" {
		title = fmt.Sprintf("Fix %s: %s", action.Signal.Kind, action.Signal.Target)
	}
	description := fmt.Sprintf("Generated by Reeve from `%s` on `%s`.", action.Signal.Kind, action.Signal.Target)
	if action.Kind == producer.ActionReopen && action.PriorTask != "" {
		description += "\n\nRegression of completed task: " + action.PriorTask
	}
	if action.Signal.Snapshot != "" {
		description += "\n\nSource snapshot:\n\n```text\n" + action.Signal.Snapshot + "\n```"
	}
	description, err := coord.AppendTrailer(description, action.Trailer)
	if err != nil {
		return CreateSpec{}, err
	}
	shortSpace := shortSpace(action.Signal.SpaceURI)
	return CreateSpec{
		Title:       title,
		Description: description,
		Tags: []string{
			"reeve",
			"axis:maintenance",
			"signal:" + action.Signal.Kind,
			"space:" + shortSpace,
			"dedup:" + producer.ShortDedup(action.DedupKey),
		},
		Workspace: workspace,
		Priority:  priority(action.Signal.Severity),
		DedupKey:  action.DedupKey,
		Action:    string(action.Kind),
		PriorTask: action.PriorTask,
	}, nil
}

func priority(severity float64) string {
	switch {
	case severity >= 0.9:
		return "p0"
	case severity >= 0.7:
		return "p1"
	case severity >= 0.4:
		return "p2"
	default:
		return "p3"
	}
}

func shortSpace(uri string) string {
	if i := strings.LastIndex(uri, "/"); i >= 0 && i+1 < len(uri) {
		return uri[i+1:]
	}
	return uri
}
